### ISSUE TITLE
Couldn't get this mod to load

### ISSUE THREAD

**Issue by Timlugia** [Cyances/Super-M60#3]
Hi, I couldn't get this mod to load in the game. Still default M60A3 with M774. Tried removed all other mod and still didn't work.
Wonder if the recent update changing M833 to 774 broke this mod?

**Comment by Cyances** [comment]
Hi, I'm investigating this issue at the moment.

**Comment by Cyances** [comment]
> Hi, I couldn't get this mod to load in the game. Still default M60A3 with M774. Tried removed all other mod and still didn't work. Wonder if the recent update changing M833 to 774 broke this mod?

Should be fixed now with latest release
https://github.com/Cyances/Super-M60/releases/tag/SM60v0.2.1

**Comment by Timlugia** [comment]
It works perfectly fine now, thank you!
If I may suggest, maybe in the future we could put ERA on M60? They did get some ERA near the end of their service.

**Comment by Cyances** [comment]
Nice to see a verification for the patch.

If I'll add ERA on the M60, I'll bundle it with the NATO ERA mod. However, I am planning to include addon/composite armor packages in this mod eventually.
